### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Quantum-Codes**
It's hard to test for me,, pls test. 

I tried to make a codeblock  

Remove commit of cname

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
TESTED! works well! Add this everywhere if u like

**Comment by Quantum-Codes** [comment]
Preview: https://quantum-codes.github.io/ninjamar.github.io/blog/python-packaging.html

**Comment by Quantum-Codes** [comment]
@ninjamar I think you missed this

**Comment by ninjamar** [comment]
> @ninjamar I think you missed this

One sec

**Comment by ninjamar** [comment]
Why did you remove CNAME?

**Comment by Quantum-Codes** [comment]
> Why did you remove CNAME?

That was messing up my github pages test..

**Comment by ninjamar** [comment]
> > Why did you remove CNAME?
> 
> That was messing up my github pages test..

Can you put it back?

**Comment by Quantum-Codes** [comment]
Done

**Comment by ninjamar** [comment]
I'l review later

**Pull request merged**
